# Generated by Django 5.0 on 2023-12-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviedata_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='image',
            field=models.ImageField(default='movies/images/default.jpg', upload_to='movies/images/'),
        ),
    ]
